---
output: pdf_document
---

```{r global_options, include=FALSE}
    knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE, dpi=300)
```

```{r}
    library(data.table)
    library(ggplot2)

    dat <- fread('toydata.b.csv')

    numx_by_propx <- ggplot(dat[,.(rank=median(rank)),by=.(propX,numX)], 
                            aes(x=factor(propX), y=rank, group=factor(numX), color=factor(numX))) +
                            geom_line(stat="identity") + xlab("Proportion of graph covered in each X") +
                            scale_color_discrete(name="Number of Xs") + ylab("Rank")
    
    numx_by_numnodes <- ggplot(dat[,.(rank=median(rank)),by=.(numNodesInput,numX)], 
                            aes(x=factor(numNodesInput), y=rank, group=factor(numX), color=factor(numX))) +
                            geom_line(stat="identity") + xlab("Number of nodes in graph before truncation") +
                            scale_color_discrete(name="Number of Xs") + ylab("Rank")

    numx_by_startnode <- ggplot(dat[,.(rank=median(rank)),by=.(startNode,numX)], 
                            aes(x=factor(startNode), y=rank, group=factor(numX), color=factor(numX))) +
                            geom_line(stat="identity") + xlab("Start each X on same of random node") +
                            scale_color_discrete(name="Number of Xs") + ylab("Rank")

```

```{r}
    print(numx_by_propx)
```

\pagebreak

```{r}
    print(numx_by_numnodes)
```

\pagebreak

```{r}
    print(numx_by_startnode)
```
