name: Release and Versioning

on:
  push:
    branches: [master]

jobs:    
 version-and-tag:
    #needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          VERSION_FILE="snafu/_version.py"
          VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' "$VERSION_FILE")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Creating release for version: $VERSION"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release for version ${{ steps.get_version.outputs.version }}
            
            See [commits](https://github.com/${{ github.repository }}/commits/master) for changes.
          draft: false
          prerelease: false

      - name: Move 'latest' tag
        run: |
          git tag -f latest
          git push origin -f latest   